# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "Warpcon 36"
email: "warpcon@gmail.com"
description: "Warpcon 36 is the 36th annual gaming convention in UCC"
# baseurl: "https://warpcon-ie.github.io/warpcon.ie/"
baseurl: "https://www.warpcon.ie"
url: "https://www.warpcon.ie"
# url: "https://warpcon-ie.github.io/warpcon.ie/"
# permalink: "/games/:title"

# Organizer Info
organizerName: "Warpcon"
organizerAlternateName: "Warpcon, an initiative by UCC Warps"
organizerDescription: "Open and volunteer geek communities who create exciting projects and share experience about Google technology with passion."
organizerEmail: "warpcon@gmail.com"
organizerLogo: "/img/seo/logos.png"
organizerLink: "https://facebook.com/WARPCON"

# Head
metaKeywords: "convention, ttrpgs, ccgs, wargames, ucc, cork, dnd, cyberpunk, magic the gathering"
twitterAccount: "@warpcon"
socialImageSrcGooglePlus: "/img/seo/logos.png"
socialImageSrcTwitter: "/img/seo/logos.png"
socialImageSrcFacebook: "/img/seo/logos.png"

# Navigation
navigationLinks:
  - {permalink: "/", text: "Home"}
  - {permalink: "/games/", text: "Games"}
  - {permalink: "/schedule", text: "Schedule"}
  # - {permalink: "/booklet.pdf", text: "Booklet"}

# bottomNavigationLinks:
#  - {link: "https://docs.google.com/forms/d/e/1FAIpQLSds7_XGjjyr1WuwuL3QSxhhg1R97B132o_IrN-EuleW2JrMsA/viewform?usp=sf_link", text: "Become a trader"}
#  - {link: "https://bit.ly/dfua-c4p", text: "Become a vendor"}
# AS FAR AS I CAN TELL THESE ^ 2 LINES OF CODE ARE USELESS BUT IM NOT DELETING THEM JUST IN CASE

rightNavigationButtons:
#  - {link: "https://docs.google.com/forms/d/e/1FAIpQLSds7_XGjjyr1WuwuL3QSxhhg1R97B132o_IrN-EuleW2JrMsA/viewform?usp=sf_link", text: "Become a trader"}
# ONLY THIS LINE OF CODE SEEMS TO BE NEEDED FOR TRADER BUTTON/FORM BUT IM LEAVING THE ONE UNDER JUST IN CASE ^^^

#  - {link: "https://bit.ly/dfua-c4p", text: "Become a vendor"}

# Hero Block
heroImage: "warpcon36-squirrel-banner.png" # TODO: Maybe change? Website is not dynamic so phone is fucked
heroTitle: "Warpcon 36"
eventDate: "January 30th - February 1st 2026"
typeoutTextValues: '"", "TTRPGs", "CCGs", "Wargames", "UCC", "Cork"'
typeoutFallback: ""
heroButtons:
# - {link: "/assets/mainhandbook.pdf", text: "Handbook"}
- {permalink: "/#tickets", text: "Tickets"} # MAKE SURE TICKET LINK IS UPDATED

# About Block
aboutTitle: "About Warpcon"
aboutBlock:
 - {title: "RPGs",          image: "ttrpgs.jpg",      text: "Many RPGs on Friday, Saturday and Sunday. <a href='https://forms.gle/TG4D5ZxwCaQ26CQk6'>Please sign up for RPG Submissions!</a>"}
 - {title: "CCGs",            image: "ccgs.jpg",        text: "Magic the Gathering, Pokémon, Yu-Gi-Oh and Lorcana events and tournaments"}
 - {title: "LARPs",           image: "larps.jpg",       text: "All weekend, we will be hosting organized LARPs events."}
 - {title: "Wargames",        image: "wargames.jpg",    text: "On Saturday and Sunday, we will be hosting <a href='/assets/40k-2024.pdf'>Warhammer 40k</a> and <a href='/assets/BleedBowl-2024.pdf'>Bloodbowl</a>. As well as LOTR and smaller tournaments"}
 - {title: "Boardgames",      image: "boardgames.jpg",  text: "Many boardgames will be available for attendees to play at any time during the convention."}
 - {title: "Charity",         image: "charity.jpg",     text: "On Saturday night, we will be holding a charity auction in the New Bar, with proceeds going to Cork Children's hospital"}
# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "gamers", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of fun games"}

 - {count: "12", specialCharacter: "", info: "rooms booked", detail: "packed full of games"}

# Latest News Block
latestNewsTitle: "Latest news"

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Devere Hall"
eventLocationLink: "https://warpcon.eventbrite.com"
eventStreetAddress: "College Road"
eventAddressLocality: "Cork City"
eventAddressLocalityRegion: "Cork"
eventPostalCode: "79000"
eventAddressCountry: "Ireland"
# eventStartTime: "2025-01-31T17:00"
# eventDoorTime: "17:00"
# eventEndTime: "2025-02-02T18:00"
eventPlaceCoordinates: "49.843237, 24.028751"
mapCenterCoordinates: "49.842537, 24.025701"
mapMobileCenterCoordinates: "49.841620, 24.029411"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "stud_centre.jpg"
venueSmallImage1: "dev_hall.jpg"
venueSmallImage2: "newbar.jpg"
venueSmallImage3: "orb.jpg"
venueTitle: "UCC Campus"
venueFeatures: ["12 rooms", "<b>Devere Hall</b> - Reception & Trader Hall", "Located upstairs in Student Centre"]

# Staff block
staffInfo:
  header: "Staff at Warpcon help ensure events run smoothly, and are a vital part of the Warpcon team."
  bodyText: "Staff are volunteers, and are not paid for their work, however; they do gain access to the event for free and will receive an exclusive Staff Warpcon T-Shirt. Staff are also eligible for complementary lunch on days they are working."
  link: https://docs.google.com/forms/d/e/1FAIpQLSfYECBFfwOUHZbnk2l59UtM09q6NW9u4IxnQWswULvYkCTTAw/viewform?usp=sf_link
  disabled: false

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "warpcon"

# Partners Block
organizersTitle: "Organizers"
partnersTitle: "Partners"
partnersC4sponsorsButton: "Become a sponsor"


# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets can also be purchased at the reception desk on the day. For college society group bookings, please contact us at <a href='mailto:warpcon@gmail.com'>warpcon@gmail.com</a>."
ticketsOffers:
 -
  name: "Weekend Pass"
  price: "€25"
  priceCurrency: "EUR"
  featured: true
  # TODO: CHANGE THIS
  buyButtonLink: "https://uccsocieties.ticketsolve.com/ticketbooth/shows/1173660198"
  buyButtonText: "Buy now!"
  ticketContentList: ["Admission to Warpcon convention","Access to CCG Tournaments", "Access to all boardgames and TTRPGs"]
  # TODO: UPDATE DATES
  #validFrom: "2025-10-01T00:00"
  #validThrough: "2025-10-23T23:59"
  validFrom: "?"
  validThrough: "?"
  disabled: true
 -
  name: "Day Pass"
  price: "€15"
  # ribbon: "Ribbon Text"
  priceCurrency: "EUR"
  featured: true
  # buyButtonLink: "https://uccsocieties.ticketsolve.com/ticketbooth/shows/1173660198"
  buyButtonText: "Buy now!"
  ticketContentList: ["Admission to Warpcon convention","Access to CCG Tournaments", "Access to all boardgames and TTRPGs"]
  # TODO: UPDATE DATES
  #validFrom: "2025-10-01T00:00"
  #validThrough: "2025-10-23T23:59"
  validFrom: "?"
  validThrough: "?"
  disabled: true

# Footer
socialLinks:
 - {link: "https://facebook.com/WARPCON",   icon: "facebook"}
 - {link: "https://instagram.com/WARPCON",  icon: "instagram"}
 - {permalink: "/feed.xml", icon: "rss"}
footerBlocks:
 -
  title: "Links"
  links:
    - {link: "https://warpcon.eventbrite.ie",         text: "Eventbrite"}
    - {link: "https://www.facebook.com/WARPCON/",     text: "Facebook"}
    - {link: "https://www.instagram.com/warpconucc/", text: "Instagram"}

 -
  title: "Contacts"
  links:
  - {link: "mailto:warpcon@gmail.com",              text: "warpcon@gmail.com"}
  - {link: "mailto:warpconrpgs@gmail.com",          text: "warpconrpgs@gmail.com"}
  - {link: "mailto:warpconccgs@gmail.com",          text: "warpconccgs@gmail.com"}
  - {link: "mailto:warpcontrade@uccsocieties.ie",   text: "warpcontrade@uccsocieties.ie"}

  # Past emails. Left for redundancy
   # - {link: "mailto:warpcondirector@gmail.com",   text: "warpcondirector@gmail.com"}
   # - {link: "mailto:warpconofficers@uccsocieties.ie",   text: "warpconofficers@uccsocieties.ie"}
   # - {link: "mailto:warpcontrader@gmail.com",     text: "warpcontrader@gmail.com"}
   # - {link: "mailto:warpconsecretary@gmail.com",  text: "warpconsecretary@gmail.com"}
   # - {link: "mailto:warpconstaff@gmail.com",      text: "warpconstaff@gmail.com"}
 -
  title: "FAQ"
  links:
   - {permalink: "/cod/", text: "Code of Conduct"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: ""

# Speakers List Block
showSessions: false
