# Plugins
plugins:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: 
  - /automation/
  - README.md
  - LICENSE.txt
  - CNAME

# Site Settings
title: "Warpcon 36"
email: "warpcon@uccsocieties.ie"
description: "Warpcon 36 is the 36th annual gaming convention in UCC"

# For local development
baseurl: ""
url: "https://www.warpcon.ie"
# permalink: "/games/:title"

# Organizer Info
# Likely useless
# organizerName: "Warpcon"
# organizerAlternateName: "Warpcon, an initiative by UCC Warps"
# organizerEmail: "warpcon@gmail.com"
# organizerLogo: "/img/seo/logos.png"
# organizerLink: "https://facebook.com/WARPCON"

# Head
metaKeywords: "convention, ttrpgs, ccgs, wargames, ucc, cork, dnd, cyberpunk, magic the gathering"
twitterAccount: "@warpcon"
socialImageSrcGooglePlus: "/img/seo/logos.png"
socialImageSrcTwitter: "/img/seo/logos.png"
socialImageSrcFacebook: "/img/seo/logos.png"

# Navigation
navigationLinks:
  - {permalink: "/", text: "Home"}
  - {permalink: "/games/", text: "Games"}
  - {permalink: "/schedule", text: "Schedule"}
  # - {permalink: "/booklet.pdf", text: "Booklet"}
  # - {permalink: "http://warpcon35.conmaps.com/", text: "Map"}

# Hero Block
heroImage: "banner.png" # TODO: Maybe change? Website is not dynamic so phone is fucked
heroTitle: "Warpcon 36"
eventDate: "January 30th - February 1st 2026"
typeoutTextValues: '"", "TTRPGs", "CCGs", "Wargames", "UCC", "Cork"'
typeoutFallback: ""
heroButtons:
# - {link: "/assets/mainhandbook.pdf", text: "Handbook"}
- {permalink: "/#tickets", text: "Tickets"} # MAKE SURE TICKET LINK IS UPDATED

# About Block
aboutTitle: "About Warpcon"
aboutBlock:
 - {title: "RPGs",          image: "ttrpgs.jpg",      text: "Many RPGs on Friday, Saturday and Sunday. <a href='https://forms.gle/TG4D5ZxwCaQ26CQk6'>Please sign up for RPG Submissions!</a>"}
 - {title: "CCGs",            image: "ccgs.jpg",        text: "Magic the Gathering, Pokémon, Yu-Gi-Oh and Lorcana events and tournaments"}
 - {title: "LARPs",           image: "larps.jpg",       text: "All weekend, we will be hosting organized LARPs events."}
 # Removed reference to specific games
 # - {title: "Wargames",        image: "wargames.jpg",    text: "On Saturday and Sunday, we will be hosting <a href='/assets/40k-2024.pdf'>Warhammer 40k</a> and <a href='/assets/BleedBowl-2024.pdf'>Bloodbowl</a>."}
 - {title: "Wargames",        image: "wargames.jpg",    text: "On Saturday and Sunday, we will be hosting some of your favourite wargames!"}
 - {title: "Boardgames",      image: "boardgames.jpg",  text: "Many boardgames will be available for attendees to play at any time during the convention."}
 - {title: "Charity",         image: "charity.jpg",     text: "On Saturday night, we will be holding a charity auction in the New Bar, with proceeds going to Cork Children's hospital"}
# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "350", specialCharacter: "+", info: "gamers", detail: "from everywhere"}
 - {count: "48", specialCharacter: "+", info: "hours", detail: "of fun games"}

 - {count: "12", specialCharacter: "", info: "rooms booked", detail: "packed full of games"}

# Location Block
locationBlockTitle: "Location"
eventLocationName: "Devere Hall"
eventLocationLink: "https://warpcon.eventbrite.com"
eventStreetAddress: "College Road"
eventAddressLocality: "Cork City"
eventAddressLocalityRegion: "Cork"
eventPostalCode: "79000"
eventAddressCountry: "Ireland"
# eventStartTime: "2025-01-31T17:00"
# eventDoorTime: "17:00"
# eventEndTime: "2025-02-02T18:00"
eventPlaceCoordinates: "49.843237, 24.028751"
mapCenterCoordinates: "49.842537, 24.025701"
mapMobileCenterCoordinates: "49.841620, 24.029411"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "stud_centre.jpg"
venueSmallImage1: "dev_hall.jpg"
venueSmallImage2: "newbar.jpg"
venueSmallImage3: "orb.jpg"
venueTitle: "UCC Campus"
venueFeatures: ["12 rooms", "<b>Devere Hall</b> - Reception & Trader Hall", "Located upstairs in Student Centre"]

# Sponsor Block
sponsorTitle: "Sponsored By"
sponsorBlock:
 - {title: "Chaosium",    image: "chaosium.png",    website: "https://www.chaosium.com/"}
 #- {title: "Placeholder", image: "chaosium.png",  website: "https://www.wikipedia.org/"}


# Staff Block
staffInfo:
  header: "Staff at Warpcon help ensure events run smoothly, and are a vital part of the Warpcon team."
  bodyText: "Staff are volunteers, and are not paid for their work, however; they do gain access to the event for free and will receive an exclusive Staff Warpcon T-Shirt. Staff are also eligible for complementary lunch on days they are working."
  link: https://docs.google.com/forms/d/e/1FAIpQLSfYECBFfwOUHZbnk2l59UtM09q6NW9u4IxnQWswULvYkCTTAw/viewform?usp=sf_link
  disabled: false

# Trader Block
traderInfo:
  header: "Traders at Warpcon offer a range of goods to attendees"
  bodyText: "Traders generally sell items related to events run at Warpcon. If you want to sign up to be a trader at Warpcon, sign up below!"
  link: https://docs.google.com/forms/d/e/1FAIpQLSc75knu0LO-22TF-W-nrkq12hxAuwOEB6uvjUcx6sxP5iwS_Q/viewform?usp=dialog
  disabled: false

# Tickets Block in tickets.yml

# Footer in footer.yml

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: ""
